### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by ntapiam** [madmurphy/libconfini#1]
I was trying to build the library on macOS Sierra 10.12.4 and had to install GNU `libtool` and `libtoolize` from [Homebrew](https://brew.sh). The thing is the commands are called `glibtool` and `glibtoolize` in order to avoid conflict with Apple's, which apparently is unrelated to GNU's, so I had to edit `autogen.sh` in order to reflect this.
Would you consider testing for this tools also in the script?

**Comment by madmurphy** [comment]
@ntapiam

Thank you for your contribution! Unfortunately `glibtool` and `glibtoolize` are BSD-specific scripts, and using them (instead of `libtool` and `libtoolize`) would make Autotools not work under GNU.

**Comment by ntapiam** [comment]
But the script could depend on an environment variable, say `LIBTOOL` with default value `libtool` so the real name of the script may be changed.
In any case, if you think is not worth the change it's ok.

**Comment by madmurphy** [comment]
No, on the contrary, I think that using a variable would be a good idea. Could you submit a sketch commit?

**Comment by madmurphy** [comment]
@ntapiam

Thanks! [Merged](https://github.com/madmurphy/libconfini/pull/2/commits/f58a51de7e802c14a555bc8450320539167cb73f) and [released](https://github.com/madmurphy/libconfini/releases/tag/1.3-5). It seems to work fine under GNU as well. Have fun with **libconfini** :)

**Comment by madmurphy** [comment]
@ntapiam

Thanks! [Merged](https://github.com/madmurphy/libconfini/pull/2/commits/f58a51de7e802c14a555bc8450320539167cb73f) and [released](https://github.com/madmurphy/libconfini/releases/tag/1.3-5). It seems to work fine under GNU as well, but [I had to fix a small problem](https://github.com/madmurphy/libconfini/commit/a8145396621024bc571651b0af498dfcbefff6ae) (maybe -- just for being sure -- you could test the fixed version under macOS as well?).

**Comment by ntapiam** [comment]
It runs fine now in macOS as well. Did a clean clone and everything ran just fine.

**Comment by madmurphy** [comment]
Very good. Thanks!
