### ISSUE TITLE
Question about calling load_ini_file() from inside the IniDispHandler

### ISSUE THREAD

**Issue by Dweller** [madmurphy/libconfini#10]
Is there a problem in calling load_ini_file() from inside iniDispHandler?.

e.g.
top.ini
[Global]
Include = child.ini

[Something]
else=here

my iniParse() function which processes the keeps its current state in the user_data..  But I seem to be unable to continue to parse the top file once the child.ini is done.

Entirely possible its my code ;-),   could you confirm if load_ini_file() is reentrant or I'm barking up the wrong tree?.

Thanks in advance

**Comment by madmurphy** [comment]
Hi Dweller! Yes, it is 100% reentrant as long you avoid editing the global variables `ini_global_...` during the parsing (and even if you do that, the impact would be limited only to the value of implicit keys and to the upper/lower case mode).

If you have any problems you can attach your code.

-- madmurphy

**Comment by madmurphy** [comment]
Hi Dweller! Yes, it is 100% reentrant as long you avoid editing the global variables `ini_global_...` during the parsing (and even if you do that, the impact would be limited only to the value assigned to implicit keys and to the lower case mode).

If you have any problems you can attach your code.

-- madmurphy
