### ISSUE TITLE
Update Installation Guide

### ISSUE THREAD

**Issue by jjochum-ELT** [madmurphy/libconfini#5]
You are not mentioning that `./autoconf.sh` must be run. The `./configure` file does not exist in the repository!

The installation guide should say to run:

```
./autogen.sh
make
make install
```

instead of:

```
./configure
make
make install
```

**Comment by madmurphy** [comment]
@jjochum-ELT

Thank you. You are right. I thought I had written a note saying something like "if `configure` is missing from your package you must generate it by running `autogen.sh`", but actually I never did.

I will add it soon.

--madmurphy
