### ISSUE TITLE
new interface function

### ISSUE THREAD

**Issue by zzs213** [madmurphy/libconfini#9]
My embedded program dynamic  generate small config data frequently.
these conig data used by another part of the same program.
So use a file to transfer the config data seems strange and too slow.

Could you give a new interface func which get config data from a "const char *"

**Comment by madmurphy** [comment]
@zzs213 That's not a bad idea! As soon as I have a bit of time free I will give it a try.

**Comment by madmurphy** [comment]
@zzs213 [Done](https://github.com/madmurphy/libconfini/releases/tag/1.10.0)! See [the manual](https://madmurphy.github.io/libconfini/html/libconfini.html).

**Comment by zzs213** [comment]
Thanks!
